services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  server:
    build: .
    depends_on:
      db:
        condition: service_started
    restart: always
    env_file:
      - config.env
    ports:
      - "3000:3000"

volumes:
  mongo-data: